_target_: module.LightningTextClassifier

num_classes: 6
hf_model: bert-base-uncased
lr: 1e-5
weight_decay: 0.1

layers_to_unfreeze: null # fit only classifier head
# example with unfreezimg additional layers
# layers_to_unfreeze:
#   bert.encoder.layer:
#     - 10
#     - 11
