defaults:
  - datamodule: baseline_datamodule
  - pl_module: baseline_module
  - logger: mlflow_logger
  - _self_

remote_dvc_repo: remote-dvc

trainer:
  deterministic: True
  max_epochs: 10
  accelerator: auto
  enable_progress_bar: True
  log_every_n_steps: 25

early_stopping_callback:
  monitor: val_f1_score
  patience: 3
  verbose: True
  mode: max

model_checkpoint_callback:
  monitor: val_f1_score
  save_top_k: 1
  mode: max
  verbose: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    env_set:
      TOKENIZERS_PARALLELISM: "false"
